export const STATUS_START = 'STATUS_START';
export const STATUS_ERROR = 'STATUS_ERROR';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_GENRES = 'FETCH_GENRES';
export const SET_GENRE_FILTER = 'SET_GENRE_FILTER';
export const SET_RATING_FILTER = 'SET_RATING_FILTER';
